anime_list=[
            {"title": "Sousou no Frieren",
             "genre": "Adventrue",
             "year": 2023},
             {"title": "Fullmetal Alchemist: Brotherhood",
             "genre": "Action",
             "year": 2009},
             {"title": "Steins;Gate",
             "genre": "Sci-Fi",
             "year": 2011},
             {"title": "Shingeki no Kyojin",
             "genre": "Action",
             "year": 2013},
             {"title": "Koe no Katachi",
             "genre": "Drama",
             "year": 2016},
             {"title": "Code Geass: Hangyaku no Lelouch",
             "genre": "Action",
             "year": 2006},
             {"title": "Monster",
             "genre": "Mystery",
             "year": 2004},
             {"title": "Bocchi the Rock!",
             "genre": "Comedy",
             "year": 2022},
             {"title": "Vinland Saga",
             "genre": "Action",
             "year": 2019},
             {"title": "One Piece",
             "genre": "Adventure",
             "year": 1999},
             {"title": "Violet Evergarden",
             "genre": "Drama",
             "year": 2018},
             {"title": "Mononoke Hime",
             "genre": "Fantasy",
             "year": 1997},
             {"title": "Mushishi",
             "genre": "Slice of life",
             "year": 2005},
             {"title": "Made in Abyss",
             "genre": "Adventure",
             "year": 2017},
             {"title": "Dungeon Meshi",
             "genre": "Comedy",
             "year": 2024},
]